title:        Riccardo Mich
tagline:      "Riccardo Mich"
url:          http://riccardomich.com
author:
  name:       "Stefano"
  email:      "michste93@gmail.com"
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     4
